config/routes.rb
Translation::Application.routes.draw do
  
  resources :translations
  resources :homes

   root :to => 'homes#index'

end

app/models/home.rb
require 'rubygems'
require 'sys/uname'
include Sys
class Home < ActiveRecord::Base

  class << self

    def agent
    	p Uname.machine
    	p Uname.version
    	p Uname.uname
  	
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
    @t = Home.agent
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render json: @home, status: :created, location: @home }
      else
        format.html { render action: "new" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/translatiolations_controller.rb
class TranslatiolationsController < ApplicationController
  def index
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  def index
  	@translations = I18n.backend.store
  end

  def create
  I18n.backend.store_translations(params[:locale], {params[:key] => params[:value]}, :escape => false)
  p "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#{I18n.backend.store_translations(params[:locale], {params[:key] => params[:value]}, :escape => false).inspect}"
  redirect_to translations_url, :notice => "Added translation"
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/translatiolations_helper.rb
module TranslatiolationsHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<%= @t%>
Goto <%= link_to 'Translations' ,translations_url %>
<h1><%= t :hello_world %><h1> <p><i>The Above Value is having a key as :hello_world</i><p>

  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

  <h1><%= t :currency %><h1> <p><i>The Above Value is having a key as :currency</i><p>
  <p>Lorem Ipsum For Currency is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Translation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/translatiolations/index.html.erb
<h1>Translatiolations#index</h1>
<p>Find me in app/views/translatiolations/index.html.erb</p>

app/views/translations/index.html.erb
Goto <%=link_to 'Home' ,root_url %>
<h1>Translations</h1>


<table border="1">
<tr>
<th>Locale.key</th>
<th>Value</th>
</tr>
<% @translations.keys.each do |key| %>
<tr >
  <td ><%= key %> </td>
  <td ><%= @translations[key] %></td>
</tr>
<%end%>
</table>



<h2>Add Translation</h2>

<%= form_tag translations_path do %>
  <p>
    <%= label_tag :locale %><br />
    <%= text_field_tag :locale %>
  </p>
  <p>
    <%= label_tag :key %><br />
    <%= text_field_tag :key %>
  </p>
  <p>
    <%= label_tag :value %><br />
    <%= text_field_tag :value %>
  </p>
  <p><%= submit_tag "Submit" %></p>
<% end %>